### ISSUE TITLE
Pickle file loading issue

### ISSUE THREAD

**Issue by eshafeeqe** [rafaelpossas/bayes_sim#1]
Dear @rafaelpossas 

Thanks for the code. I was trying your code for running an experiment but it seems pickle file is not loading properly. I am getting following error. 

```
Traceback (most recent call last):
  File "/home/rl_tests/domain_randomization/bayes_sim/pendulum_param_inference.py", line 11, in <module>
    g = PendulumDataGenerator(policy_file=policy_file, load_from_file=False)
  File "/home/rl_tests/domain_randomization/bayes_sim/src/data/pendulum_data_generator.py", line 31, in __init__
    self.policy = PPO2.load(policy_file)
  File "/home/.virtualenvs/bysim_env/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 938, in load
    data, params = cls._load_from_file(load_path, custom_objects=custom_objects)
  File "/home/.virtualenvs/bysim_env/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 689, in _load_from_file
    data, params = BaseRLModel._load_from_file_cloudpickle(load_path)
  File "/home/.virtualenvs/bysim_env/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 623, in _load_from_file_cloudpickle
    data, params = cloudpickle.load(file_)
_pickle.UnpicklingError: invalid load key, 'v'.
Current Directory: /home/rl_tests/domain_randomization/bayes_sim
```

I am using cloudpickle version of 0.8.0.
Any help in this is really appreciated.

**Comment by rafaelpossas** [comment]
Hi Shafeeq,

The Pickle files are stored with Git LFS, you need to enable it and tell it
to download the files, you probably have the placeholders for now

Regards
